### ISSUE TITLE
General authentication

### ISSUE THREAD

**Issue by juroc95** [juroc95/walktober#20]
Acceptance criteria:
- login page (username/email, password, sign in) (no CSS / may work with Yifan)
- registration page (email, first name, last name, password, re-enter password, sign up) (no CSS / may work with Yifan)
- completion of registration should create a new user in firestore database and authentication on firebase
- completion of registration should be redirected to login page
- users should be able to sign in with the appropriate username/email and password
- failure of sign in should be redirected to login page
- completion of sign in should be directed to home page
- should be able to manage user info on both firestore database and authentication on firebase

helpful link: https://www.youtube.com/watch?v=jCY6DH8F4oc&list=LL&index=2&t=899s&ab_channel=PedroTech

frontend design: [Brainstorming.pdf](https://github.com/juroc95/walktober/files/10028331/Brainstorming.pdf)

**Comment by bailee-crandley** [comment]
@juroc95 @marobertson11 I just want to double check to make sure you guys aren't doing the same work as my front end team. You shouldn't be creating the login and registration page. That is part of the front end. You should be creating the endpoints that we can hit so that once the frontend gathers the data from the user, we can pass it to the backend and it can do what ever it's supposed to do. So for this one, the frontend will gather the username and password and pass it to the backend to authenticate.

**Comment by juroc95** [comment]
@bailee-crandley We are creating the basic login and registration page just to make it easier for Michael and Yifan to work on the backend part. Once we are done, we will integrate it with the login and registration page that the frontend team created.
